# Generated by Django 3.0.2 on 2020-01-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='date_created',
        ),
    ]
