# Generated by Django 3.0.2 on 2020-01-28 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_todoitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.TextField(),
        ),
    ]
